version: '3.8'

services:
  # 1. GoLang API Servisi
  go-api:
    build: ./backend-go
    ports:
      - "8080:8080" # Bilgisayarının 8080 portunu container'ın 8080 portuna bağla
    volumes:
      - ./backend-go:/app # Kodda değişiklik yaptığında anında yansıması için
    depends_on:
      - postgres-db
      - neo4j
      - elasticsearch
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=osintuser
      - DB_PASSWORD=osintpass
      - DB_NAME=osint_sources
    networks:
      - osint-net

  # 2. Python Veri İşleme Servisi
  python-worker:
    build: ./backend-python
    ports:
      - "8000:8000"
    volumes:
      - ./backend-python:/app
    depends_on:
      - postgres-db
      - neo4j
      - elasticsearch
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=osintuser
      - DB_PASSWORD=osintpass
      - DB_NAME=osint_sources
    networks:
      - osint-net

  # 3. Frontend Servisi
  frontend:
    build: ./frontend-react
    ports:
      - "3000:80" # Bilgisayarının 3000 portunu container'ın 80 portuna bağla
    depends_on:
      - go-api
    networks:
      - osint-net

  # 4. Neo4j Graf Veri Tabanı
  neo4j:
    image: neo4j:5 # Hazır Neo4j imajını kullanıyoruz
    ports:
      - "7474:7474" # Neo4j Browser arayüzü
      - "7687:7687" # Bolt driver bağlantısı
    environment:
      - NEO4J_AUTH=osintadmin/Wololo--13202923596 # Kullanıcı adı: neo4j, Şifre: Wololo--13202923596
    depends_on:
      - elasticsearch
    volumes:
      - neo4j_data:/data # Verilerin kalıcı olması için volume
    networks:
      - osint-net

  # 5. Elasticsearch Arama Motoru
  elasticsearch:
    image: elasticsearch:8.14.0 # Hazır Elasticsearch imajı
    ports:
      - "9200:9200" # REST API portu
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Geliştirme ortamı için güvenliği kapatıyoruz
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - osint-net

  # 6. PostgreSQL Veritabanı
  postgres-db:
    image: postgres:16-alpine # Hafif bir postgres imajı
    ports:
      - "5432:5432" # Standart PostgreSQL portu
    environment:
      - POSTGRES_USER=osintadmin
      - POSTGRES_PASSWORD=Wololo--45976830800
      - POSTGRES_DB=osint_sources
    volumes:
      - postgres_data:/var/lib/postgresql/data # Verilerin kalıcı olması için
    networks:
      - osint-net

# Tüm container'ların birbiriyle konuşabilmesi için ortak bir ağ tanımlıyoruz
networks:
  osint-net:
    driver: bridge

# Verilerin kalıcı olmasını sağlayan volume'ları tanımlıyoruz
volumes:
  neo4j_data:
  elasticsearch_data:
  postgres_data: